# Generated by Django 2.1.7 on 2019-04-01 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline_name', models.CharField(max_length=100, unique=True)),
                ('aircraft_type', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_location', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('country_name', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField(blank=True, default='', max_length=100)),
                ('departure_time', models.CharField(blank=True, default='', max_length=100)),
                ('ticket_price', models.IntegerField()),
                ('executive_capacity', models.IntegerField()),
                ('turist_capacity', models.IntegerField()),
                ('airline_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kayak_app.Airline', to_field='airline_name')),
                ('arrive_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive_airport_name', to='kayak_app.Airport', to_field='airport_name')),
                ('departure_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departure_airport_name', to='kayak_app.Airport', to_field='airport_name')),
                ('destiny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destiny_state_location', to='kayak_app.Country', to_field='state_location')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_state_location', to='kayak_app.Country', to_field='state_location')),
            ],
            options={
                'ordering': ('ticket_price',),
            },
        ),
        migrations.CreateModel(
            name='TravelClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.CharField(blank=True, default='', max_length=100)),
                ('class_price', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='airport',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='kayak_app.Country'),
        ),
        migrations.AddField(
            model_name='airport',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='kayak_app.Country'),
        ),
    ]
